import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  // puma

  {
    _id: uuid(),
    name: "Sparx",
    description: "Sparx Shoes For Men Sm-322 (black, Grey)",
    price: 825,
    qty: 1,
    category: "male",
    color: "white",
    rating: {
      rate: 5,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: true,
    original_price: 1499,
    discount: 45,
    img: "https://www.askmea2z.com/inventory_images/1751.jpg",
    categoryName: "sneakers",
  },

  {
    _id: uuid(),
    name: "adidas",
    description: "adidas all running shoes",
    price: 809,
    qty: 1,
    category: "male",
    color: "grey",
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: false,
    original_price: 899,
    discount: 10,
    img: "https://images.sportsdirect.com/images/products/21125169_3pl.jpg",
    categoryName: "sports",
  },

  {
    _id: uuid(),
    name: "Puma",
    description: "Puma Shoes, Fast Cat Sneakers ",
    price: 1649,
    qty: 1,
    category: "male",
    color: "grey",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: true,
    original_price: 2499,
    discount: 40,
    img: "https://i.pinimg.com/originals/b7/a6/76/b7a676d97d2cb1057158a228b2a724cf.jpg",
    categoryName: "sneakers",
  },
  {
    _id: uuid(),
    name: "Air Max",
    description: "Nike Men Air Max 90 Qs",
    price: 949,
    qty: 1,
    category: "male",
    color: "multi-color",
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: true,
    original_price: 1199,
    discount: 10,
    img: "	https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1610382629-air-max-iii-mens-shoe-lxZhs3.jpg",
    categoryName: "casual",
  },
  {
    _id: uuid(),
    name: "adidas",
    description: "EQ21 Run Navy Shoes",
    price: 1599,
    qty: 1,
    category: "male",
    color: "white",
    rating: {
      rate: 1,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: false,
    original_price: 1999,
    discount: 20,
    img: "	https://www.efootwear.eu/media/catalog/product/cache/image/800x800/0/0/0000209409130_01_ks.jpg",
    categoryName: "sneakers",
  },
  {
    _id: uuid(),
    name: "Air Max",
    description: "Mens Nike Air Max",
    price: 5950,
    qty: 1,
    category: "male",
    color: "white",
    rating: {
      rate: 2,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: false,
    best_seller: false,
    original_price: 6999,
    discount: 15,
    img: "	https://s7d2.scene7.com/is/image/academy/20662968?$d-plp-product-image$",
    categoryName: "casual",
  },

  {
    _id: uuid(),
    name: "Sparx",
    description: "SPARX SLIPPERS FOR MEN SFG-1072",
    price: 599,
    qty: 1,
    category: "male",
    color: "white",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: false,
    original_price: 799,
    discount: 25,
    img: "	https://dxkvlfvncvqr8.cloudfront.net/media/product-image/SFG-1072-BLBL-1.jpg",
    categoryName: "crocs",
  },
  {
    _id: uuid(),
    name: "Liberty",
    description: "Liberty Formal Shoes For Man",
    price: 1059,
    qty: 1,
    category: "male",
    color: "white",
    rating: {
      rate: 5,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: true,
    original_price: 1199,
    discount: 20,
    img: "	https://content.woodlandworldwide.com/static/images/products/16517/main-fgf0180u3842a-black-1.jpg",
    categoryName: "formals",
  },
  {
    _id: uuid(),
    name: "Liberty",
    description: "Liberty Formal Shoes For Woman",
    price: 1349,
    qty: 1,
    category: "female",
    color: "white",
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: true,
    original_price: 1499,
    discount: 10,
    img: "https://4.imimg.com/data4/LI/HS/MY-12665633/ladies-shoes-500x500.jpg",
    categoryName: "formals",
  },
  {
    _id: uuid(),
    name: "Puma",
    description: "Black Formal Shoes For Kids",
    price: 675,
    qty: 1,
    category: "kids",
    color: "white",
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: true,
    original_price: 899,
    discount: 25,
    img: "https://5.imimg.com/data5/LR/WL/VE/SELLER-26286062/kids-leather-shoes-250x250.jpg",
    categoryName: "formals",
  },

  {
    _id: uuid(),
    name: "Sparx",
    description: "Sparx Sport Shoes For Women",
    price: 779,
    qty: 1,
    category: "female",
    color: "pink",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: false,
    original_price: 1199,
    discount: 35,
    img: "https://tarakonline.com/upload/ProductColor/RealImage/2971(SS)LSP1PISL139(8).jpg",
    categoryName: "sports",
  },

  {
    _id: uuid(),
    name: "Sparx",
    description: "Sparx Women SL-115 Red White Casual Shoes",
    price: 559,
    qty: 1,
    category: "female",
    color: "pink",
    rating: {
      rate: 2,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: false,
    original_price: 799,
    discount: 30,
    img: "https://images-eu.ssl-images-amazon.com/images/I/41BwS0cU6wL.jpg",
    categoryName: "sports",
  },
  {
    _id: uuid(),
    name: "Puma",
    description: "PUMA Men's Suede Classic",
    price: 1799,
    qty: 1,
    category: "male",
    color: "white-black",
    rating: {
      rate: 5,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: true,
    original_price: 2999,
    discount: 40,
    img: "https://footwearnews.com/wp-content/uploads/2019/08/puma-suede-classic-sneaker.jpg",
    categoryName: "sneakers",
  },
  {
    _id: uuid(),
    name: "Sparx",
    description: "Asian ELASTO-02 EVA Women Sports Shoes",
    price: 279,
    qty: 1,
    category: "female",
    color: "pink",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: false,
    original_price: 549,
    discount: 48,
    img: "https://5.imimg.com/data5/OC/KN/II/SELLER-3678405/elasto-02-eva-sports-shoes-women-500x500.jpeg",
    categoryName: "sports",
  },
  {
    _id: uuid(),
    name: "Air Max",
    description: "Mens Casual Air Max",
    price: 1999,
    qty: 1,
    category: "male",
    color: "multi-color",
    rating: {
      rate: 5,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: false,
    original_price: 3999,
    discount: 50,
    img: "https://classic.cdn.media.amplience.net/i/hibbett/5P449_3055_right2?w=300&h=300&img404=404&v=1",
    categoryName: "casual",
  },

  {
    _id: uuid(),
    name: "Air Max",
    description: "Allen Solly Grey Lace Up Shoes",
    price: 1649,
    qty: 1,
    category: "female",
    color: "pink",
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: true,
    original_price: 2999,
    discount: 45,
    img: "	https://cdn2.stylicy.com/global/image-5764-158137241-1-big-hr.jpg",
    categoryName: "casual",
  },

  {
    _id: uuid(),
    name: "Liberty",
    description: "Asics Women's Glideride 2 Standard Cream Running Shoes",
    price: 6499,
    qty: 1,
    category: "female",
    color: "grey",
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: false,
    best_seller: true,
    original_price: 12999,
    discount: 50,
    img: "https://thumbs.dreamstime.com/b/funky-canvas-shoes-yellow-white-202724035.jpg",
    categoryName: "sneakers",
  },

  {
    _id: uuid(),
    name: "Liberty",
    description: "Archlight Slingback Pump",
    price: 2080,
    qty: 1,
    category: "female",
    color: "pink",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: false,
    original_price: 2599,
    discount: 20,
    img: "https://eu.louisvuitton.com/images/is/image/lv/1/P…t-slingback-pump--AN5E1ESSRR_PM2_Front%20view.jpg",
    categoryName: "crocs",
  },

  {
    _id: uuid(),
    name: "Liberty",
    description: "Double White Casual Flip Flops",
    price: 1199,
    qty: 1,
    category: "female",
    color: "pink",
    rating: {
      rate: 1,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: false,
    original_price: 1999,
    discount: 40,
    img: "https://kxadmin.metroshoes.com/product/351-9002/550/351-9002M16.jpg",
    categoryName: "crocs",
  },

  {
    _id: uuid(),
    name: "adidas",
    description: "Classic Penny Loafer Moccasin",
    price: 1499,
    qty: 1,
    category: "female",
    color: "grey",
    rating: {
      rate: 2,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: true,
    original_price: 2999,
    discount: 50,
    img: "	https://i8.amplience.net/i/hotter/SAILZSOFTBLU-LE",
    categoryName: "casual",
  },

  {
    _id: uuid(),
    name: "adidas",
    description: "Stylish Kids Shoes",
    price: 499,
    qty: 1,
    category: "kids",
    color: "blue",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: true,
    original_price: 799,
    discount: 40,
    img: "	https://5.imimg.com/data5/PW/DS/GT/SELLER-65814696/kids-shoes-500x500.jpg",
    categoryName: "casual",
  },

  {
    _id: uuid(),
    name: "adidas",
    description:
      "Kids Shoes with Wheels LED Light Color Shoes Shiny Roller Skates",
    price: 1599,
    qty: 1,
    category: "kids",
    color: "pink",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: false,
    original_price: 2999,
    discount: 45,
    img: "https://m.media-amazon.com/images/I/710vHRPuILL._AC_UL1500_.jpg",
    categoryName: "casual",
  },

  {
    _id: uuid(),
    name: "Puma",
    description: "Tennis 1977 sneakers",
    price: 1999,
    qty: 1,
    category: "kids",
    color: "grey",
    rating: {
      rate: 5,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: false,
    original_price: 3499,
    discount: 45,
    img: "	https://cdn-images.farfetch-contents.com/17/62/10/86/17621086_36741822_300.jpg",
    categoryName: "sneakers",
  },

  {
    _id: uuid(),
    name: "Puma",
    description: "Wave Zone Kids Crocs",
    price: 499,
    qty: 1,
    category: "kids",
    color: "blue",
    rating: {
      rate: 2,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: true,
    original_price: 899,
    discount: 40,
    img: "	https://footwearnews.com/wp-content/uploads/2021/08/Screen-Shot-2021-08-06-at-8.55.19-AM.png?w=876",
    categoryName: "crocs",
  },
  {
    _id: uuid(),
    name: "Puma",
    description: "Men's Puma Pacer Future Alumni Slip-On Sneakers",
    price: 4339,
    qty: 1,
    category: "male",
    color: "white",
    rating: {
      rate: 3,
      count: 5,
    },
    fast_delivery: false,
    in_stocks: true,
    best_seller: false,
    original_price: 6999,
    discount: 38,
    img: "	https://i8.amplience.net/s/scvl/123228_260556_SET/1?fmt=auto&$webPlp$",
    categoryName: "sports",
  },
  {
    _id: uuid(),
    name: "Sparx",
    description: "Sparx Shoes For Kids",
    price: 549,
    qty: 1,
    category: "kids",
    color: "pink",
    rating: {
      rate: 5,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: false,
    best_seller: false,
    original_price: 799,
    discount: 30,
    img: "	https://dxkvlfvncvqr8.cloudfront.net/media/product-image/SK-526-BLGN-1.jpg",
    categoryName: "sports",
  },

  {
    _id: uuid(),
    name: "Sparx",
    description: "Sparx Shoes For Kids",
    price: 649,
    qty: 1,
    category: "kids",
    color: "white",
    original_price: 899,
    rating: {
      rate: 4,
      count: 5,
    },
    fast_delivery: true,
    in_stocks: true,
    best_seller: true,
    discount: 30,
    img: "	https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQH6jJBBTOdfJfUDtOz3M_VwkfptnRC8hIwkg&usqp=CAU",
    categoryName: "sneakers",
  },
];
